export const universitiesList = [
  { value: "University of Aberdeen", label: "University of Aberdeen" },
  { value: "Abertay University", label: "Abertay University" },
  { value: "Aberystwyth University", label: "Aberystwyth University" },
  { value: "Anglia Ruskin University", label: "Anglia Ruskin University" },
  { value: "Arden University", label: "Arden University" },
  { value: "Aston University", label: "Aston University" },
  { value: "Bangor University", label: "Bangor University" },
  { value: "University of Bath", label: "University of Bath" },
  { value: "Bath Spa University", label: "Bath Spa University" },
  { value: "University of Bedfordshire", label: "University of Bedfordshire" },
  { value: "BIMM University", label: "BIMM University" },
  { value: "University of Birmingham", label: "University of Birmingham" },
  { value: "Birmingham City University", label: "Birmingham City University" },
  {
    value: "University College Birmingham",
    label: "University College Birmingham",
  },
  {
    value: "Bishop Grosseteste University",
    label: "Bishop Grosseteste University",
  },
  { value: "University of Bolton", label: "University of Bolton" },
  {
    value: "Arts University Bournemouth",
    label: "Arts University Bournemouth",
  },
  { value: "Bournemouth University", label: "Bournemouth University" },
  { value: "BPP University", label: "BPP University" },
  { value: "University of Bradford", label: "University of Bradford" },
  { value: "University of Brighton", label: "University of Brighton" },
  { value: "University of Bristol", label: "University of Bristol" },
  { value: "Brunel University London", label: "Brunel University London" },
  { value: "University of Buckingham", label: "University of Buckingham" },
  {
    value: "Buckinghamshire New University",
    label: "Buckinghamshire New University",
  },
  { value: "University of Cambridge", label: "University of Cambridge" },
  {
    value: "Canterbury Christ Church University",
    label: "Canterbury Christ Church University",
  },
  {
    value: "Cardiff Metropolitan University",
    label: "Cardiff Metropolitan University",
  },
  { value: "Cardiff University", label: "Cardiff University" },
  { value: "University of Chester", label: "University of Chester" },
  { value: "University of Chichester", label: "University of Chichester" },
  { value: "Coventry University", label: "Coventry University" },
  { value: "Cranfield University", label: "Cranfield University" },
  {
    value: "University for the Creative Arts",
    label: "University for the Creative Arts",
  },
  { value: "University of Cumbria", label: "University of Cumbria" },
  { value: "De Montfort University", label: "De Montfort University" },
  { value: "University of Derby", label: "University of Derby" },
  { value: "University of Dundee", label: "University of Dundee" },
  { value: "Durham University", label: "Durham University" },
  { value: "University of East Anglia", label: "University of East Anglia" },
  { value: "University of East London", label: "University of East London" },
  { value: "Edge Hill University", label: "Edge Hill University" },
  { value: "University of Edinburgh", label: "University of Edinburgh" },
  {
    value: "Edinburgh Napier University",
    label: "Edinburgh Napier University",
  },
  { value: "University of Essex", label: "University of Essex" },
  { value: "University of Exeter", label: "University of Exeter" },
  { value: "Falmouth University", label: "Falmouth University" },
  { value: "University of Glasgow", label: "University of Glasgow" },
  {
    value: "Glasgow Caledonian University",
    label: "Glasgow Caledonian University",
  },
  {
    value: "University of Gloucestershire",
    label: "University of Gloucestershire",
  },
  { value: "University of Greenwich", label: "University of Greenwich" },
  { value: "Harper Adams University", label: "Harper Adams University" },
  { value: "Hartpury University", label: "Hartpury University" },
  { value: "Heriot-Watt University", label: "Heriot-Watt University" },
  {
    value: "University of Hertfordshire",
    label: "University of Hertfordshire",
  },
  {
    value: "University of the Highlands and Islands",
    label: "University of the Highlands and Islands",
  },
  { value: "University of Huddersfield", label: "University of Huddersfield" },
  { value: "University of Hull", label: "University of Hull" },
  { value: "Imperial College London", label: "Imperial College London" },
  { value: "Keele University", label: "Keele University" },
  { value: "University of Kent", label: "University of Kent" },
  { value: "Kingston University", label: "Kingston University" },
  {
    value: "University of Central Lancashire",
    label: "University of Central Lancashire",
  },
  { value: "Lancaster University", label: "Lancaster University" },
  { value: "University of Leeds", label: "University of Leeds" },
  { value: "Leeds Arts University", label: "Leeds Arts University" },
  { value: "Leeds Beckett University", label: "Leeds Beckett University" },
  { value: "Leeds Trinity University", label: "Leeds Trinity University" },
  { value: "University of Leicester", label: "University of Leicester" },
  { value: "University of Lincoln", label: "University of Lincoln" },
  { value: "University of Liverpool", label: "University of Liverpool" },
  { value: "Liverpool Hope University", label: "Liverpool Hope University" },
  {
    value: "Liverpool John Moores University",
    label: "Liverpool John Moores University",
  },
  { value: "University of London", label: "University of London" },
  {
    value: "London Metropolitan University",
    label: "London Metropolitan University",
  },
  {
    value: "London School of Economics[a]",
    label: "London School of Economics[a]",
  },
  {
    value: "London South Bank University",
    label: "London South Bank University",
  },
  { value: "Loughborough University", label: "Loughborough University" },
  { value: "University of Manchester", label: "University of Manchester" },
  {
    value: "Manchester Metropolitan University",
    label: "Manchester Metropolitan University",
  },
  { value: "Middlesex University", label: "Middlesex University" },
  { value: "Newcastle University", label: "Newcastle University" },
  { value: "Newman University", label: "Newman University" },
  { value: "University of Northampton", label: "University of Northampton" },
  {
    value: "Northeastern University – London",
    label: "Northeastern University – London",
  },
  { value: "Northumbria University", label: "Northumbria University" },
  {
    value: "Norwich University of the Arts",
    label: "Norwich University of the Arts",
  },
  { value: "University of Nottingham", label: "University of Nottingham" },
  {
    value: "Nottingham Trent University",
    label: "Nottingham Trent University",
  },
  { value: "The Open University", label: "The Open University" },
  { value: "University of Oxford", label: "University of Oxford" },
  { value: "Oxford Brookes University", label: "Oxford Brookes University" },
  { value: "Plymouth Marjon University", label: "Plymouth Marjon University" },
  { value: "Arts University Plymouth", label: "Arts University Plymouth" },
  { value: "University of Plymouth", label: "University of Plymouth" },
  { value: "University of Portsmouth", label: "University of Portsmouth" },
  { value: "Queen Margaret University", label: "Queen Margaret University" },
  { value: "Queen's University Belfast", label: "Queen's University Belfast" },
  { value: "Ravensbourne University", label: "Ravensbourne University" },
  { value: "University of Reading", label: "University of Reading" },
  { value: "Regent's University London", label: "Regent's University London" },
  {
    value: "Richmond American University London",
    label: "Richmond American University London",
  },
  { value: "Robert Gordon University", label: "Robert Gordon University" },
  { value: "Roehampton University", label: "Roehampton University" },
  {
    value: "Royal Agricultural University",
    label: "Royal Agricultural University",
  },
  {
    value: "Royal Holloway, University of London",
    label: "Royal Holloway, University of London",
  },
  { value: "University of Salford", label: "University of Salford" },
  { value: "University of Sheffield", label: "University of Sheffield" },
  {
    value: "Sheffield Hallam University",
    label: "Sheffield Hallam University",
  },
  { value: "University of South Wales", label: "University of South Wales" },
  { value: "University of Southampton", label: "University of Southampton" },
  { value: "Solent University", label: "Solent University" },
  { value: "University of St Andrews", label: "University of St Andrews" },
  {
    value: "St George's, University of London",
    label: "St George's, University of London",
  },
  {
    value: "St Mary's University, Twickenham",
    label: "St Mary's University, Twickenham",
  },
  { value: "Staffordshire University", label: "Staffordshire University" },
  { value: "University of Stirling", label: "University of Stirling" },
  { value: "University of Strathclyde", label: "University of Strathclyde" },
  { value: "University of Suffolk", label: "University of Suffolk" },
  { value: "University of Sunderland", label: "University of Sunderland" },
  { value: "University of Surrey", label: "University of Surrey" },
  { value: "University of Sussex", label: "University of Sussex" },
  { value: "Swansea University", label: "Swansea University" },
  { value: "Teesside University", label: "Teesside University" },
  {
    value: "University of the Arts London",
    label: "University of the Arts London",
  },
  { value: "Ulster University", label: "Ulster University" },
  { value: "University of Law", label: "University of Law" },
  { value: "University of Wales", label: "University of Wales" },
  {
    value: "University of Wales Trinity Saint David",
    label: "University of Wales Trinity Saint David",
  },
  { value: "University of Warwick", label: "University of Warwick" },
  {
    value: "University of the West of England",
    label: "University of the West of England",
  },
  {
    value: "University of the West of Scotland",
    label: "University of the West of Scotland",
  },
  { value: "University of West London", label: "University of West London" },
  { value: "University of Westminster", label: "University of Westminster" },
  { value: "University of Winchester", label: "University of Winchester" },
  {
    value: "University of Wolverhampton",
    label: "University of Wolverhampton",
  },
  { value: "University of Worcester", label: "University of Worcester" },
  { value: "Wrexham Glyndŵr University", label: "Wrexham Glyndŵr University" },
  { value: "University of York", label: "University of York" },
  { value: "York St John University", label: "York St John University" },
];
